CC = gcc
CFLAGS = -Wall -std=c99
SRC = main.c ingrediente.c pizza.c
OBJ = $(SRC:.c=.o)
EXEC = pizzaria

all: $(EXEC)

$(EXEC): $(OBJ)
	$(CC) $(OBJ) -o $(EXEC)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJ) $(EXEC)

run: $(EXEC)
	./$(EXEC)

.PHONY: all clean run
